directories:
  - ../terraform/vpc/beforegoingd_apnortheast2
  - ../terraform/networking/teamund/beforegoingd_apnortheast2
  - ../terraform/ecs/teamund/beforegoingd_apnortheast2
  - ../terraform/lambda/teamund/beforegoingd_apnortheast2